// Generated by CoffeeScript 1.7.1
(function() {
  var count, lastNightGame, noSoRealResult, result, result2, unitedStates, worldCup, worldCupYear;

  $('#pirates').click(function() {
    return alert("give me your money");
  });

  $('#abandonShip').click(function() {
    return alert("sharks");
  });

  count = 0;

  $('#submarine').click(function() {
    console.log(count);
    count = count + 1;
    return $('#submarineCount').html(count);
  });

  $('#restart').click(function() {
    $('#submarineCount').html(0);
    return count = 0;
  });

  worldCup = $('.germany h1').html();

  alert(worldCup);

  worldCupYear = $('.germany p').html();

  alert(worldCupYear);

  lastNightGame = $('.germany h2').html();

  alert(lastNightGame);

  unitedStates = $('.germany h3').html();

  alert(unitedStates);

  result = $('.germany h4').html();

  console.log(result);

  noSoRealResult = $('.germany p').last().html();

  console.log(noSoRealResult);

  result2 = $('.result').html();

  console.log(result2);

}).call(this);

//# sourceMappingURL=main.map
